### ISSUE TITLE
ASAN failure: //consensus/bundle_validator/tests:bundle_validator

### ISSUE THREAD

**Issue by th0br0** [iotaledger/entangled#333]
```
Executing tests from //consensus/bundle_validator/tests:bundle_validator
-----------------------------------------------------------------------------

=================================================================
==15==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f76f760e848 in __interceptor_malloc (/lib64/libasan.so.5+0xef848)
    #1 0x7f76f72582ba in trit_array_new common/trinary/trit_array.c:85
    #2 0x40228b in test_bundle_exceed_supply_pos_invalid consensus/bundle_validator/tests/bundle_validator.c:160
    #3 0x7f76f71f5447 in UnityDefaultTestRun external/unity/src/unity.c:1339
    #4 0x403766 in main consensus/bundle_validator/tests/bundle_validator.c:381
    #5 0x7f76f6d47412 in __libc_start_main (/lib64/libc.so.6+0x24412)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f76f760e848 in __interceptor_malloc (/lib64/libasan.so.5+0xef848)
    #1 0x7f76f72582ba in trit_array_new common/trinary/trit_array.c:85
    #2 0x402746 in test_bundle_exceed_supply_neg_invalid consensus/bundle_validator/tests/bundle_validator.c:204
    #3 0x7f76f71f5447 in UnityDefaultTestRun external/unity/src/unity.c:1339
    #4 0x403781 in main consensus/bundle_validator/tests/bundle_validator.c:382
    #5 0x7f76f6d47412 in __libc_start_main (/lib64/libc.so.6+0x24412)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f76f760e848 in __interceptor_malloc (/lib64/libasan.so.5+0xef848)
    #1 0x7f76f72582ba in trit_array_new common/trinary/trit_array.c:85
    #2 0x402d6e in test_bundle_validate_size_4_value_wrong_sig_invalid consensus/bundle_validator/tests/bundle_validator.c:270
    #3 0x7f76f71f5447 in UnityDefaultTestRun external/unity/src/unity.c:1339
    #4 0x40379c in main consensus/bundle_validator/tests/bundle_validator.c:383
    #5 0x7f76f6d47412 in __libc_start_main (/lib64/libc.so.6+0x24412)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f76f760e848 in __interceptor_malloc (/lib64/libasan.so.5+0xef848)
    #1 0x7f76f72582ba in trit_array_new common/trinary/trit_array.c:85
    #2 0x401dc4 in test_bundle_size_1_value_with_wrong_address_invalid consensus/bundle_validator/tests/bundle_validator.c:116
    #3 0x7f76f71f5447 in UnityDefaultTestRun external/unity/src/unity.c:1339
    #4 0x40374b in main consensus/bundle_validator/tests/bundle_validator.c:380
    #5 0x7f76f6d47412 in __libc_start_main (/lib64/libc.so.6+0x24412)

SUMMARY: AddressSanitizer: 128 byte(s) leaked in 4 allocation(s).
```

**Comment by tsvisabo** [comment]
Fixed by #340
